app/Http/routes.php
<?php

use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Redis;
use RFS_Manager\Event;
use RFS_Manager\Events\EventCreated;
use RFS_Manager\Events\EventRecieved;
use RFS_Manager\Events\NewEventRecieved;
use RFS_Manager\Events\UserHasRegistered;
use RFS_Manager\Http\Requests\EventRequest;
use RFS_Manager\Http\Requests\Request;
use RFS_Manager\Member;
use RFS_Manager\User;
use RFS_Manager\jobs\SendAlert;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as' => 'home', 'uses' => 'DashboardController@index']);
Route::get('/calls', ['as' => 'events', 'uses' => 'EventController@index']);
Route::get('/calls/new', 'EventController@create');
Route::post('/calls', ['as' => 'event_store', 'uses' => 'EventController@store']);
Route::get('/test', ['as' => 'test', 'uses' => 'EventController@test']);
Route::get('/calls/response', ['as' => 'sms.response', 'uses' => 'EventController@response']);
Route::get('/calls/send', ['as'=>'repeater', 'uses'=>'EventController@repeater']);
Route::get('/init', ['as'=>'init', 'uses'=>'MemberController@init']);
Route::get('/assign/{id}', ['as'=>'qualifications.assign', 'uses'=>'QualificationController@assign']);
Route::post('/assign/{id}', 'MemberController@store_assignment');
Route::get('/unassign/{mid}/{qid}', ['as'=>'qualifications.unnassign','uses'=>'MemberController@remove_assignment']);
Route::get('/types/assign/{id}', ['as'=>'types.assign', 'uses'=>'TypeController@assign']);
Route::post('/types/assign/{id}', 'TypeController@store_assignment');
Route::post('/api/event', 'EventController@callback');

Route::get('socket', 'EventController@viewEvent');
Route::post('sendmessage', 'EventController@sendEvent');
Route::get('writemessage', 'EventController@writeEvent');
Route::get('twilio_response', 'EventController@twilioResponse');

Route::resource('types', 'TypeController');
Route::resource('users', 'AccessController');
Route::resource('qualifications', 'QualificationController');
Route::resource('members', 'MemberController');

Route::get('/types/{type}/{qshort}', ['as'=>'types.unnassign', 'uses'=>'TypeController@remove_assignment']);


Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

// Route::get('/testmessage', 'DashboardController@response');
Route::get('/testmessage', function() {
	$event = Event::all()->first();
    Event::fire(new EventCreated($event));
});

Route::get('/fullscreen', ['as'=>'full_screen','uses'=>'DashboardController@fullscreen']);

// Route::post('/api/event/test', 'EventController@writeFile');

resources/views/accounts/create.blade.php
@extends('dashboard')

@section('sidebar')
    <div class="sidebar">
        <ul>
            <li><a href="{{route('home')}}"><i class="fa fa-user"></i>Dashboard</a></li>
            <li><a href="{{route('events')}}"><i class="fa fa-file-text"></i>Fire Calls</a></li>
            <li><a href="{{route('users.index')}}" class="active"><i class="fa fa-users"></i>User Accounts</a></li>
            <li><a href="{{route('members.index')}}"><i class="fa fa-lightbulb-o"></i>Members</a></li>
            <li><a href="{{route('qualifications.index')}}"><i class="fa fa-graduation-cap"></i>Qualifications</a></li>
            <li><a href="{{route('types.index')}}"><i class="fa fa-fire"></i>Fire Call Types</a></li>
        </ul>
    </div>
@endsection

@section('content')
@include('partials.form-alerts')
<div class="panel">
            <div class="title">
                <p>New Account</p>
            </div>

    {!! Form::model($user, array('action' => array('AccessController@store', $user))) !!}
        @include('accounts.form', ['buttonText' => 'Create Account'])
    {!! Form::close() !!}
</div>
@endsection

resources/views/accounts/edit.blade.php
@extends('dashboard')

@section('sidebar')
    <div class="sidebar">
        <ul>
            <li><a href="{{route('home')}}"><i class="fa fa-user"></i>Dashboard</a></li>
            <li><a href="{{route('events')}}"><i class="fa fa-file-text"></i>Fire Calls</a></li>
            <li><a href="{{route('users.index')}}" class="active"><i class="fa fa-users"></i>User Accounts</a></li>
            <li><a href="{{route('members.index')}}"><i class="fa fa-lightbulb-o"></i>Members</a></li>
            <li><a href="{{route('qualifications.index')}}"><i class="fa fa-graduation-cap"></i>Qualifications</a></li>
            <li><a href="{{route('types.index')}}"><i class="fa fa-fire"></i>Fire Call Types</a></li>
        </ul>
    </div>
@endsection

@section('content')
@if ($errors->any())
    <ul class="form-alert">
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
@endif
<div class="panel">
            <div class="title">
                <p>Edit Account</p>
            </div>
    {!! Form::model($user, array('route' =>  array('users.update', $user), 'method' => 'PATCH', 'class' => 'form-horizontal')) !!}
		@include('accounts.form', ['buttonText'=>'Update Account'])
    {!! Form::close() !!}
</div>
@endsection

resources/views/accounts/form.blade.php
    {!! Form::hidden('id', $user->id) !!}
    <div class="input-group">
        {!! Form::label('name', 'Name', array('class'=>'control-label'))!!}
        <div class="col-sm-6">
            {!! Form::text('name', null, array('class'=>'form-control', 'placeholder'=>'name'))!!}
        </div>
    </div>
    <div class="input-group">
        {!! Form::label('email', 'Email Address', array('class'=>'control-label'))!!}
        <div class="col-sm-6">
        {!! Form::text('email', null, array('class' => 'form-control', 'placeholder'=>'email'))!!}
        </div>
    </div>

    <div class="input-group">
        {!! Form::label('password', 'Password', array('class'=>'control-label'))!!}
        <div class="col-sm-6">
        {!! Form::password('password', array('class' => 'form-control', 'placeholder'=>'password'))!!}
        </div>
    </div>

    <div class="input-group">
        {!! Form::label('password_confirmation', 'Password Confirmation', array('class'=>'control-label'))!!}
        <div class="col-sm-6">
        {!! Form::password('password_confirmation', array('class' => 'form-control', 'placeholder'=>'password_confirmation'))!!}
        </div>
    </div>

    <div class="input-group">
        <button type="submit">{{$buttonText}}</button>
    </div>

resources/views/accounts/index.blade.php
@extends('dashboard')

@section('sidebar')
    <div class="sidebar">
        <ul>
            <li><a href="{{route('home')}}"><i class="fa fa-user"></i>Dashboard</a></li>
            <li><a href="{{route('events')}}"><i class="fa fa-file-text"></i>Fire Calls</a></li>
            <li><a href="{{route('users.index')}}" class="active"><i class="fa fa-users"></i>User Accounts</a></li>
            <li><a href="{{route('members.index')}}"><i class="fa fa-lightbulb-o"></i>Members</a></li>
            <li><a href="{{route('qualifications.index')}}"><i class="fa fa-graduation-cap"></i>Qualifications</a></li>
            <li><a href="{{route('types.index')}}"><i class="fa fa-fire"></i>Fire Call Types</a></li>
        </ul>
    </div>
@endsection

@section('content')
<div class="panel">
            <div class="title">
                <span>User Accounts</span><a id="add_account_button" href="{{route('users.create')}}">Add Account</a>
            </div>
                <table>
                    <tr><th>Name</th><th>Email</th><th></th><th>&nbsp;</th></tr>
                    @foreach($accounts as $account)
                    <tr><td>{{$account->name}}</td><td>{{$account->email}}</td><td><a href="{{route('users.edit', $account->id)}}">Edit</a></td><td><a>Delete</a></td></tr>
                    @endforeach
                </table>
            </div>

<!-- <div class="row center">
    <table class="center">
    @foreach($accounts as $account)
        <tr><td><b>name:</b></td><td>{{$account->name}}</td><td><b>username:</b></td><td>{{$account->email}}</td><td><a class="btn btn-default" href="{{route('users.edit', $account->id)}}">Edit</a></td><td>{!! Form::open(array('route' => array('users.destroy', $account->id), 'method' => 'delete')) !!}<button class="btn btn-default" type="submit">Remove</button>{!! Form::close() !!}</td></tr>
    @endforeach
    </table>
</div> -->
@endsection

resources/views/accounts/show.blade.php
@extends('dashboard')

@section('sidebar')
    <div class="sidebar">
        <ul>
            <li><a href="{{route('home')}}"><i class="fa fa-user"></i>Dashboard</a></li>
            <li><a href="{{route('events')}}"><i class="fa fa-file-text"></i>Fire Calls</a></li>
            <li><a href="{{route('users.index')}}" class="active"><i class="fa fa-users"></i>User Accounts</a></li>
            <li><a href="{{route('members.index')}}"><i class="fa fa-lightbulb-o"></i>Members</a></li>
            <li><a href="{{route('qualifications.index')}}"><i class="fa fa-graduation-cap"></i>Qualifications</a></li>
            <li><a href="{{route('types.index')}}"><i class="fa fa-fire"></i>Fire Call Types</a></li>
        </ul>
    </div>
@endsection

@section('content')
		<p class="user-accounts"><span><b>name:</b> {{$account->name}}</span>&nbsp;&nbsp;<span><b>username:</b> {{$account->email}}</span>&nbsp;&nbsp;<a class="btn btn-primary" href="{{route('users.edit', $account->id)}}">Edit</a>&nbsp;&nbsp;<a class="btn btn-danger" href="{{route('users.destroy', $account->id)}}">Delete</a></p>
@endsection